### ISSUE TITLE
Error with create_aircraft.py

### ISSUE THREAD

**Issue by StepLogic** [DLR-SC/tigl-examples#2]
fuselage = fuselages.create_fuselage("fuselage", 5, "fuselageCircleProfileuID")
AttributeError: 'CCPACSFuselages' object has no attribute 'create_fuselage'
Please I am getting this error when i run create_aircraft.py

**Comment by joergbrech** [comment]
It sounds like you might be using tigl instead of cpacscreator. Could this be the case? If yes, check out the installation instructions for cpacscreator with Anaconda here: https://github.com/DLR-SC/tigl-examples/blob/master/tigl/python/cpacscreator-animation/README.md

cpacscreator is in a prerelease state, the cpacs editing/creation features will be added to tigl some time in the future.

**Comment by StepLogic** [comment]
Thanks Fixed it,i had tigl installed
